### ISSUE TITLE
用CocoaPod引入后，会有一个2.3MB的资源文件，这个是不需要的

### ISSUE THREAD

**Issue by yongyuegao** [upyun/ios-sdk#10]
![image](https://cloud.githubusercontent.com/assets/8231246/21975071/85db2f64-dc05-11e6-8991-ae3a91662462.png)

用CocoaPod引入后，会有一个2.3MB的资源文件，这个是不需要的，增大了包的体积，请删除一下

**Comment by roveretoa** [comment]
@yongyuegao  这个已经修改了，请使用：pod 'UPYUN', '~> 1.0.3'
