### ISSUE TITLE
使用 UIImage 和 NSData 上传，无法填充save-key 中存储路径的 suffix 字段

### ISSUE THREAD

**Issue by Whirlwind** [upyun/ios-sdk#11]
例如我期望存储路径为 `savekey: "/headimg/{year}/{mon}/{day}/c0974f7a-627a-44d6-9a70-dc977beb3447{.suffix}"`，这里要求有一个后缀，但是程序中一般从PHAsset中拿到的就已经是UIImage了，无法传递filepath信息进去。而重新将UIImage保存为文件再让SDK读取出来，是一个很奇怪的逻辑，性能上也差不少。

期望修改SDK的接口，能增加虚拟路径传递入口，解决 filename 和 suffix 无法识别的问题。

**Comment by roveretoa** [comment]
@Whirlwind 请问，你的 savekey 是本地生成，还是服务器统一设置的？如果是本地生成的，建议还是自主替换掉```{.suffix}``` 比较好。这种直接传递 “data“ 情况本质上就是没有路径的，加一个“虚拟路径”参数不太科学。(上传三种接口‘image、data、filepath’统一再多加个”filename“参数，倒是可取）

**Comment by Whirlwind** [comment]
savekey 是服务端生成的。你所说的filename参数和我说的“虚拟路径”好像是一个意思。

**Comment by linKnowEasy** [comment]
增加了一个  filename 字段。 使用方法可以看 demo  VC 的 93-95 行
`    UIImage *image = [UIImage imageNamed:@"Default"];
    [uy uploadFile:image saveKey:[NSString stringWithFormat:@"/{year}/{mon}/c0974f7a-627a-44d6-9a70-dc977beb3447{.suffix}"] fileName:@"aa.png" extParams:nil];
`
如果使用 pod 安装的话。建议删除重新安装.
