### ISSUE TITLE
Demo 和 SDK 内容有不同导致 出现 signature error

### ISSUE THREAD

**Issue by binbinah** [upyun/ios-sdk#15]
Demo 里面: [https://github.com/upyun/ios-sdk/blob/master/UpYunSDKDemo/UpYunSDKDemo/UpYunSDK/class/UpLoader/UpYunFormUploader.m#L103](https://github.com/upyun/ios-sdk/blob/master/UpYunSDKDemo/UpYunSDKDemo/UpYunSDK/class/UpLoader/UpYunFormUploader.m#L103)

SDK 里面: [https://github.com/upyun/ios-sdk/blob/master/UpYunSDK/class/UpLoader/UpYunFormUploader.m#L103](https://github.com/upyun/ios-sdk/blob/master/UpYunSDK/class/UpLoader/UpYunFormUploader.m#L103)

麻烦看看这里是不是需要修正一下, 这一行的 ```@"%@/%@/"``` Demo中和SDK中相差一个 '/'

**Comment by roveretoa** [comment]
@binbinah https://github.com/upyun/ios-sdk/commit/8d7f4893118aa37c25699a9549ed0741b9596a72

修改了。
文件夹组织错误，重复了。其中一个是不在工程管理之下的无效文件夹。现在保留了一份并且是最新代码。

"/" 引起的签名错误。虽然带 "/" 本地签名也能上传成功，但是服务器签名时候会因为 url 不一致而产生签名验证失败。文档标准是不带 “/” 的：http://docs.upyun.com/api/form_api/

上次这个问题的提交：https://github.com/upyun/ios-sdk/commit/956b4c885f09746150f2098b773267552630e50b
