### ISSUE TITLE
视频裁剪相关， iOS

### ISSUE THREAD

**Issue by anwent** [upyun/ios-sdk#17]
按照文档写的，想截取视频的前两秒，显示成功，但是在Upyun Manager 这个应用里没有找到裁剪完的URL，是哪里出了问题？
![4d892d82-071b-4625-8887-f9d4929b3f70](https://user-images.githubusercontent.com/15354932/30312588-c6117906-975f-11e7-91c4-3961498b7014.png)

**Comment by linKnowEasy** [comment]
截图成功之后的图片 url ，和上传成功一样, 将 saveKey  / (task 中的 save_as)  进行 url 拼接即可得到

**Comment by anwent** [comment]
怎么拼？给个例子可以吗？

**Comment by linKnowEasy** [comment]
https://%@.b0.upaiyun.com/%@", bucketName,  save_as     // 这里的 save_as 就是 task 中的save_as, 即你发的图片中的  "test.webp"

和下图一样, 最后的 字段为 save_as (即  test.webp ) 
![image](https://user-images.githubusercontent.com/8413135/30313233-3b04e7ce-97cf-11e7-987e-81b4e86ecbc7.png)

**Comment by anwent** [comment]
还是不行。

**Comment by linKnowEasy** [comment]
不行是指什么情况？？  方便先试试 demo 么？

![image](https://user-images.githubusercontent.com/8413135/30313990-ddb6212a-97d1-11e7-9324-7588a962c281.png)
