### ISSUE TITLE
iOS11 iPhone X设备图片使用了HEIC格式, 导出LivePhoto后, 图片打不开

### ISSUE THREAD

**Issue by yangyu2010** [upyun/ios-sdk#18]
在iPhone7以下, 或者ios11以下设备, 不支持HEIC格式

**Comment by linKnowEasy** [comment]
能问下具体的 场景和操作么 
iOS11 iPhone X, 在导出时,  HEIC 格式的时候. 可以选择 转化为其他的格式, 

对于照片，从 HEVC 转换为 JPG 比较简单，通过 PhotoKit 的接口获取 NSData，结合 UIImageJPEGRepresentation 就可以转换

@yangyu2010

**Comment by yangyu2010** [comment]
你好, 具体场景我简单描述下, 我使用了sdk上传了LivePhoto图片, 当前测试设备为iPhone X, 图片格式为HEIC, 上传也没问题. 这时, 我拿了一个iPhone 6s, 系统为10.3.3的, 下载当前LivePhoto资源, 发现图片和视频合成不了LivePhoto了. 我在网上查了相关信息具体如下:
https://zhuanlan.zhihu.com/p/24077346
https://stackoverflow.com/questions/32508375/apple-live-photo-file-format
大致的问题就是, LivePhoto需要图片和视频配对起来, 不然就合成不了.

**Comment by yangyu2010** [comment]
使用UIImageJPEGRepresentation方法应该可以解决问题, 但是我用的方法是requestImageForAsset, 稍后看看怎么修改成你那方法测试下. @linKnowEasy

**Comment by linKnowEasy** [comment]
好的,麻烦你了. 
我们这边也看看是否有更合适的方法 @yangyu2010

**Comment by yangyu2010** [comment]
一般上传的过程都是先把图片资源copy到本地来, 使用如下方法

```
// Handlers are called on[ an arbitrary serial queue.
- (void)writeDataForAssetResource:(PHAssetResource *)resource
                           toFile:(NSURL *)fileURL
                          options:(nullable PHAssetResourceRequestOptions *)options
                completionHandler:(void(^)(NSError *__nullable error))completionHandler;]
```

这样会把图片, 视频资源直接copy来, 这个时候我是直接上传到云端, 没有经过处理. 还是得对图片视频进行处理.

**Comment by linKnowEasy** [comment]
可以在上传前做一下处理.  @yangyu2010 
可以修改`UpYun.m` 中  上传 livephoto `uploadLivePhoto......` 代码
```
//  [self uploadFile:PATH_PHOTO_FILE saveKey:[NSString stringWithFormat:@"%@.jpg",saveKey]];
    NSData *fileData = [NSData dataWithContentsOfFile:PATH_PHOTO_FILE];
    UIImage *img = [UIImage imageWithData:fileData];
    [self uploadFile:img saveKey:[NSString stringWithFormat:@"%@.jpg",saveKey]];
    
```
