### ISSUE TITLE
- `AFNetworking (~> 2.3)` required by `UpYunSDK (2.0.1)`

### ISSUE THREAD

**Issue by DreamXiao** [upyun/ios-sdk#3]
/usr/local/bin/pod install

Analyzing dependencies
[!] Unable to satisfy the following requirements:
- `AFNetworking` required by `Podfile`
- `AFNetworking` required by `Podfile`
- `AFNetworking (= 3.1.0)` required by `Podfile.lock`
- `AFNetworking (~> 2.3)` required by `UpYunSDK (2.0.1)`

**Comment by DreamXiao** [comment]
我用的是AFNetWorking3.1

**Comment by linKnowEasy** [comment]
你好, 文档上的是 pod 'UPYUN', '~> 1.0.0' 
没有 2.0.1 版本,
我们查看过了,  UpYunSDK (2.0.1) 为一个个人开发者所 上传.
-> UpYunSDK (2.0.1)
   UpYunSDK
   pod 'UpYunSDK', '~> 2.0.1'
- Homepage: https://github.com/nickcheng/UpYunSDK/
- Source:   https://github.com/nickcheng/UpYunSDK.git
- Versions: 2.0.1 [master repo]

然后建议直接使用源码, 定制化程度高一点
