### ISSUE TITLE
demo中上传成功后,图片的路径是什么,怎么好吃拼接之后不能查看图片呢

### ISSUE THREAD

**Issue by Easyzhan** [upyun/ios-sdk#5]

**Comment by linKnowEasy** [comment]
http://bucket.b0.upaiyun.com 拼上 save key
如 bucket 为 test654123 , savekey 为 /picture.jpg
访问地址为 : http://test654123.b0.upaiyun.com/picture.jpg
http https 都行
也可以自己配置 bucket 服务, 通过自己的域名直接访问, 详情可以咨询我们 https://www.upyun.com/index.html , 底部有联系方式

**Comment by Easyzhan** [comment]
多谢,知道了,建议demo中进行一些说明吧-.-

**Comment by linKnowEasy** [comment]
@Easyzhan  OK, 后续更新版本会在 demo 写上说明
