### ISSUE TITLE
1.0.2 版本已存在

### ISSUE THREAD

**Issue by Whirlwind** [upyun/ios-sdk#9]
仓库中已经存在 v1.0.2 的tag，且CocoaPods存在了1.0.2版本，指向 v1.0.2 这个节点。请更新版本、统一tag。。。

**Comment by roveretoa** [comment]
@Whirlwind  
 pod 'UPYUN', '~> 1.0.3'


UPYUN (1.0.2) 的 podspec 无法 push 更新，原指向 tag 没法修改了。现在请用 1.0.3 吧，见谅。
